"""Add dates, notes, and ordering to Destination

Revision ID: d5b520d1eb11
Revises: 5c9498916ba8
Create Date: 2025-11-17 13:27:10.496027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b520d1eb11'
down_revision = '5c9498916ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_date', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.drop_column('order_index')
        batch_op.drop_column('notes')
        batch_op.drop_column('visit_date')

    # ### end Alembic commands ###
